export const offileData = () => [
  {
    type: "ITEM",
    id: "XDINYHJHK6MMXDR5ZKYPL4MY",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Additional massage",
      abbreviation: "+Mas",
      labelColor: "694F9C",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "E5NYBHJ52LKM6AHRYMSV6LDN",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "XDINYHJHK6MMXDR5ZKYPL4MY",
            name: "10 minutes",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "1500",
              currency: "USD",
            },
            serviceDuration: "600000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
        {
          type: "ITEM_VARIATION",
          id: "JHUEK4SRHV3PXWZ7WAAL6NGX",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "XDINYHJHK6MMXDR5ZKYPL4MY",
            name: "20 minutes",
            ordinal: 2,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "3000",
              currency: "USD",
            },
            serviceDuration: "1200000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
    },
  },
  {
    type: "ITEM",
    id: "46VW5CV5N7FEFETBWFRUWCMU",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Basic manicure",
      description:
        "Cuticle care ● File & buff ● Trimming & shaping ●  Massage ● Hot towel wrap",
      abbreviation: "BM",
      labelColor: "86B73E",
      categoryId: "42Q7FDU26NEHTPIAL66WRWTA",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "QCYYVVONTEE6IERVEVD3NGLG",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "46VW5CV5N7FEFETBWFRUWCMU",
            name: "Regular polish",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "3500",
              currency: "USD",
            },
            serviceDuration: "2100000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
        {
          type: "ITEM_VARIATION",
          id: "SQSZY2IK7ISZFILW5PSGXSAO",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "46VW5CV5N7FEFETBWFRUWCMU",
            name: "Gel polish",
            ordinal: 2,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "5000",
              currency: "USD",
            },
            serviceDuration: "3000000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMCwFyeMexqTdxw4",
              "TMSzK-FIQ2k6FSEU",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Cuticle care ● File &amp; buff ● Trimming &amp; shaping ●  Massage ● Hot towel wrap</p>",
      descriptionPlaintext:
        "Cuticle care ● File & buff ● Trimming & shaping ●  Massage ● Hot towel wrap",
    },
  },
  {
    type: "ITEM",
    id: "KB4EPIZOVAE77GWHQ2DIXHOA",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Basic pedicure",
      description:
        "Calming soak ● Cuticle care ● File & buff ● Trimming & shaping ● Mineral salt/sugar exfoliation ● Callus treatment ● Massage ● Hot towel wrap",
      abbreviation: "BP",
      labelColor: "E76132",
      availableOnline: false,
      availableForPickup: false,
      availableElectronically: false,
      categoryId: "CDCJXC5L5ZXRLEFKABSE7PVX",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "ULABSZTGZ3PCFGHLKQFXB2OY",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "KB4EPIZOVAE77GWHQ2DIXHOA",
            name: "Regular polish",
            ordinal: 0,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "5000",
              currency: "USD",
            },
            locationOverrides: [
              {
                locationId: "LS1VH64H9SA5C",
                trackInventory: false,
              },
            ],
            serviceDuration: "3000000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMCwFyeMexqTdxw4",
              "TMSzK-FIQ2k6FSEU",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
        {
          type: "ITEM_VARIATION",
          id: "7F6YCJSN23VBZHKB6ZHPVN4P",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "KB4EPIZOVAE77GWHQ2DIXHOA",
            name: "Gel polish",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "6500",
              currency: "USD",
            },
            locationOverrides: [
              {
                locationId: "LS1VH64H9SA5C",
                trackInventory: false,
              },
            ],
            serviceDuration: "3600000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMCwFyeMexqTdxw4",
              "TMSzK-FIQ2k6FSEU",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Calming soak ● Cuticle care ● File &amp; buff ● Trimming &amp; shaping ● Mineral salt/sugar exfoliation ● Callus treatment ● Massage ● Hot towel wrap</p>",
      descriptionPlaintext:
        "Calming soak ● Cuticle care ● File & buff ● Trimming & shaping ● Mineral salt/sugar exfoliation ● Callus treatment ● Massage ● Hot towel wrap",
    },
  },
  {
    type: "ITEM",
    id: "MF6RGWC2HAH6ZDH32BPUXTFZ",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Callus removal with softening agent",
      description:
        "Makes use of a softening agent. Leaves your soles soft, smooth and sandal-ready.",
      abbreviation: "Callu",
      labelColor: "694F9C",
      availableOnline: false,
      availableForPickup: false,
      availableElectronically: false,
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "QRU6WT52RAZA5OGZLM46OR3V",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "MF6RGWC2HAH6ZDH32BPUXTFZ",
            name: "Regular",
            ordinal: 0,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "1500",
              currency: "USD",
            },
            locationOverrides: [
              {
                locationId: "LS1VH64H9SA5C",
                trackInventory: false,
              },
            ],
            serviceDuration: "900000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Makes use of a softening agent. Leaves your soles soft, smooth and sandal-ready.</p>",
      descriptionPlaintext:
        "Makes use of a softening agent. Leaves your soles soft, smooth and sandal-ready.",
    },
  },
  {
    type: "ITEM",
    id: "QHU3RHZTYBAE6HZDGTMVBT3A",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Cat eye",
      description:
        "Diagonal line drawn directly through the middle of your nail, and much like actual cat eyes, the lines vary.",
      abbreviation: "Cat",
      labelColor: "694F9C",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "XV4THWU43IZB3FZKH6PJFJR2",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "QHU3RHZTYBAE6HZDGTMVBT3A",
            name: "Regular",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "2000",
              currency: "USD",
            },
            serviceDuration: "1200000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Diagonal line drawn directly through the middle of your nail, and much like actual cat eyes, the lines vary.</p>",
      descriptionPlaintext:
        "Diagonal line drawn directly through the middle of your nail, and much like actual cat eyes, the lines vary.",
    },
  },
  {
    type: "ITEM",
    id: "SWITQPNXUX4YTF6MILBPSF23",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Child manicure (ages 9 and under)",
      description: "A light version of our Basic manicure.",
      abbreviation: "Chi-M",
      labelColor: "694F9C",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "4TDOBB5Z54KAN4BLL2EC44BS",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "SWITQPNXUX4YTF6MILBPSF23",
            name: "Regular",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "2000",
              currency: "USD",
            },
            serviceDuration: "1200000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMCwFyeMexqTdxw4",
              "TMSzK-FIQ2k6FSEU",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml: "<p>A light version of our Basic manicure.</p>",
      descriptionPlaintext: "A light version of our Basic manicure.",
    },
  },
  {
    type: "ITEM",
    id: "AVSWADHL5VNFQUBD3T7M2XO3",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Child pedicure (ages 9 and under)",
      abbreviation: "Chi-P",
      labelColor: "694F9C",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "HYI6DFLWDZDGI5NUPRA27IXJ",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "AVSWADHL5VNFQUBD3T7M2XO3",
            name: "Regular",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "3000",
              currency: "USD",
            },
            serviceDuration: "1800000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
    },
  },
  {
    type: "ITEM",
    id: "BAJDJMVWNPP4VCSEHNKEIKIQ",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Chrome",
      description: "Shimmery sheen, often overtop a base color.",
      abbreviation: "Chrom",
      labelColor: "694F9C",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "3IIO6EVCEI6MPZ4HVQ2IZZKB",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "BAJDJMVWNPP4VCSEHNKEIKIQ",
            name: "Regular",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "2000",
              currency: "USD",
            },
            serviceDuration: "900000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMCwFyeMexqTdxw4",
              "TMSzK-FIQ2k6FSEU",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml: "<p>Shimmery sheen, often overtop a base color.</p>",
      descriptionPlaintext: "Shimmery sheen, often overtop a base color.",
    },
  },
  {
    type: "ITEM",
    id: "MOFVUHPGK3ZVSR7CNNJSNXRR",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Express manicure (No Polish)",
      description:
        "Cut, file & buff, lotion, hot towel treatment and cuticle oil.",
      abbreviation: "ExM",
      labelColor: "694F9C",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "7XYZHR4VA2F5GHXQ32HAJGXQ",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "MOFVUHPGK3ZVSR7CNNJSNXRR",
            name: "Regular",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "2500",
              currency: "USD",
            },
            serviceDuration: "1200000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMIQc1wsPFZN1Omk",
              "TMCwFyeMexqTdxw4",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Cut, file &amp; buff, lotion, hot towel treatment and cuticle oil.</p>",
      descriptionPlaintext:
        "Cut, file & buff, lotion, hot towel treatment and cuticle oil.",
    },
  },
  {
    type: "ITEM",
    id: "QTX6B446L6MJ4HZ6QAXEX55M",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Express pedicure (No Polish)",
      description:
        "Soak, cut, file & buff, scrub, lotion, hot towel treatment and cuticle oil.",
      abbreviation: "ExP",
      labelColor: "694F9C",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "4HOCHRSJUX7UVR7QXB6VLF23",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "QTX6B446L6MJ4HZ6QAXEX55M",
            name: "Regular",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "3500",
              currency: "USD",
            },
            serviceDuration: "1500000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMIQc1wsPFZN1Omk",
              "TMCwFyeMexqTdxw4",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Soak, cut, file &amp; buff, scrub, lotion, hot towel treatment and cuticle oil.</p>",
      descriptionPlaintext:
        "Soak, cut, file & buff, scrub, lotion, hot towel treatment and cuticle oil.",
    },
  },
  {
    type: "ITEM",
    id: "MTOERTVIAWN3QZYDDTJVS5A3",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "French tip",
      description: "Classic shape with a perfect white tipped finish.",
      abbreviation: "Frenc",
      labelColor: "694F9C",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "6HEMZMSNWZOTGDZ2ZEIKBUTD",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "MTOERTVIAWN3QZYDDTJVS5A3",
            name: "Regular",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "2000",
              currency: "USD",
            },
            serviceDuration: "1200000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMCwFyeMexqTdxw4",
              "TMSzK-FIQ2k6FSEU",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Classic shape with a perfect white tipped finish.</p>",
      descriptionPlaintext: "Classic shape with a perfect white tipped finish.",
    },
  },
  {
    type: "ITEM",
    id: "OP5RTYNTZ4TRHSII2KQQOB6E",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Luxe manicure",
      description:
        "Cuticle care ● File & buff ● Trimming & shaping ● Extended massage with extra premium care products ● Hydration mask ● Hot towel wrap ● HERMES™ or CHANEL™ care & polish selection.",
      abbreviation: "LM",
      labelColor: "86B73E",
      categoryId: "42Q7FDU26NEHTPIAL66WRWTA",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "OALYBRBGG4OPIYRRLY6S65GB",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "OP5RTYNTZ4TRHSII2KQQOB6E",
            name: "HERMES™ care selection",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "9500",
              currency: "USD",
            },
            serviceDuration: "2700000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
        {
          type: "ITEM_VARIATION",
          id: "EANQUEYQXUMFH4LKZ42TFMUC",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "OP5RTYNTZ4TRHSII2KQQOB6E",
            name: "CHANEL™ care selection",
            ordinal: 2,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "9500",
              currency: "USD",
            },
            serviceDuration: "2700000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
        {
          type: "ITEM_VARIATION",
          id: "ZONF2HKDE2RTT7TJKEFHMCGM",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "OP5RTYNTZ4TRHSII2KQQOB6E",
            name: "Gel polish",
            ordinal: 3,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "9500",
              currency: "USD",
            },
            serviceDuration: "3600000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Cuticle care ● File &amp; buff ● Trimming &amp; shaping ● Extended massage with extra premium care products ● Hydration mask ● Hot towel wrap ● HERMES™ or CHANEL™ care &amp; polish selection.</p>",
      descriptionPlaintext:
        "Cuticle care ● File & buff ● Trimming & shaping ● Extended massage with extra premium care products ● Hydration mask ● Hot towel wrap ● HERMES™ or CHANEL™ care & polish selection.",
    },
  },
  {
    type: "ITEM",
    id: "62JHCTZN5JGZ6KDLELNYBDJX",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Luxe pedicure",
      description:
        "Calming soak ● Cuticle care ● File & buff ● Trimming & shaping ● Mineral salt/sugar exfoliation ● Callus treatment ● Collagen & keratin therapy socks ● Extended massage with extra premium care products ● Hot towel wrap ● HERMES™ or CHANEL™ care & polish selection",
      abbreviation: "LP",
      labelColor: "E76132",
      categoryId: "CDCJXC5L5ZXRLEFKABSE7PVX",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "OVUVMTNKQBPG2GOJW7IPPLYI",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "62JHCTZN5JGZ6KDLELNYBDJX",
            name: "HERMES™ care selection",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "14500",
              currency: "USD",
            },
            serviceDuration: "4800000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
        {
          type: "ITEM_VARIATION",
          id: "7U34HUVGZ3CXXKQTN5SCYMWP",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "62JHCTZN5JGZ6KDLELNYBDJX",
            name: "CHANEL™ care selection",
            ordinal: 2,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "14500",
              currency: "USD",
            },
            serviceDuration: "4800000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
        {
          type: "ITEM_VARIATION",
          id: "EBAGLNOIX4YVBQ6LV3MBQZ76",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "62JHCTZN5JGZ6KDLELNYBDJX",
            name: "Gel polish",
            ordinal: 3,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "14500",
              currency: "USD",
            },
            serviceDuration: "5100000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Calming soak ● Cuticle care ● File &amp; buff ● Trimming &amp; shaping ● Mineral salt/sugar exfoliation ● Callus treatment ● Collagen &amp; keratin therapy socks ● Extended massage with extra premium care products ● Hot towel wrap ● HERMES™ or CHANEL™ care &amp; polish selection</p>",
      descriptionPlaintext:
        "Calming soak ● Cuticle care ● File & buff ● Trimming & shaping ● Mineral salt/sugar exfoliation ● Callus treatment ● Collagen & keratin therapy socks ● Extended massage with extra premium care products ● Hot towel wrap ● HERMES™ or CHANEL™ care & polish selection",
    },
  },
  {
    type: "ITEM",
    id: "TJM4ZJRT7PJUKXURVM2NLRFP",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Nail fix",
      description:
        "Temporarily fixes a broken or cracked nail until the natural nail regrows in length.",
      abbreviation: "NFix",
      labelColor: "694F9C",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "V4B26VUWS6JUKJEHYE7TAEVQ",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "TJM4ZJRT7PJUKXURVM2NLRFP",
            name: "Regular",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "1000",
              currency: "USD",
            },
            serviceDuration: "1800000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMIQc1wsPFZN1Omk",
              "TMCwFyeMexqTdxw4",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Temporarily fixes a broken or cracked nail until the natural nail regrows in length.</p>",
      descriptionPlaintext:
        "Temporarily fixes a broken or cracked nail until the natural nail regrows in length.",
    },
  },
  {
    type: "ITEM",
    id: "RL3GOHPQWBJHKWENFD3GHKDU",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Removal: acrylic, dip, hard gel ( With Service )",
      abbreviation: "A-Rem",
      labelColor: "694F9C",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "XHRSG6GAPSX4BKIDSA6YQA5M",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "RL3GOHPQWBJHKWENFD3GHKDU",
            name: "Regular",
            ordinal: 0,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "1500",
              currency: "USD",
            },
            serviceDuration: "1200000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
    },
  },
  {
    type: "ITEM",
    id: "XPOMIFUBDR4XMOZWGV44ZJKE",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Removal: gel polish",
      abbreviation: "G-Rem",
      labelColor: "694F9C",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "BNEC3KDSFO3D3DYPD7BQOYLW",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "XPOMIFUBDR4XMOZWGV44ZJKE",
            name: "Regular",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "500",
              currency: "USD",
            },
            serviceDuration: "600000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMCwFyeMexqTdxw4",
              "TMSzK-FIQ2k6FSEU",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
    },
  },
  {
    type: "ITEM",
    id: "ZGYJZBNCF7UOH7QOC6IM4YGU",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Select manicure",
      description:
        "Cuticle care ● File & buff ● Trimming & shaping ● Extended massage ● Hydration mask ● Hot towel wrap",
      abbreviation: "SM",
      labelColor: "86B73E",
      categoryId: "42Q7FDU26NEHTPIAL66WRWTA",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "CVQOS44HKTDW5U4K23AIMV2O",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "ZGYJZBNCF7UOH7QOC6IM4YGU",
            name: "Regular polish",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "5500",
              currency: "USD",
            },
            serviceDuration: "2700000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
        {
          type: "ITEM_VARIATION",
          id: "DG74PZI7MBNY6ITBIHWADDEO",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "ZGYJZBNCF7UOH7QOC6IM4YGU",
            name: "Gel polish",
            ordinal: 2,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "7000",
              currency: "USD",
            },
            serviceDuration: "3600000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Cuticle care ● File &amp; buff ● Trimming &amp; shaping ● Extended massage ● Hydration mask ● Hot towel wrap</p>",
      descriptionPlaintext:
        "Cuticle care ● File & buff ● Trimming & shaping ● Extended massage ● Hydration mask ● Hot towel wrap",
    },
  },
  {
    type: "ITEM",
    id: "FECI7HYLOOHJULRHN5IPQVIY",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Select pedicure",
      description:
        "Calming soak ● Cuticle care ● File & buff ● Trimming & shaping ● Mineral salt/sugar exfoliation ● Callus treatment ● Collagen & keratin therapy socks ● Extended massage ● Hot towel wrap",
      abbreviation: "SP",
      labelColor: "E76132",
      categoryId: "CDCJXC5L5ZXRLEFKABSE7PVX",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "KBEJ4MVTDUJCXJ2FR5XKXGWJ",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "FECI7HYLOOHJULRHN5IPQVIY",
            name: "Regular polish",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "7500",
              currency: "USD",
            },
            serviceDuration: "4500000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMCwFyeMexqTdxw4",
              "TMSzK-FIQ2k6FSEU",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
        {
          type: "ITEM_VARIATION",
          id: "XFXQRN4JDNUHI7N3GTF6E3CI",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "FECI7HYLOOHJULRHN5IPQVIY",
            name: "Gel polish",
            ordinal: 2,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "9000",
              currency: "USD",
            },
            serviceDuration: "4500000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMJjPtHVjfPG_dCo",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Calming soak ● Cuticle care ● File &amp; buff ● Trimming &amp; shaping ● Mineral salt/sugar exfoliation ● Callus treatment ● Collagen &amp; keratin therapy socks ● Extended massage ● Hot towel wrap</p>",
      descriptionPlaintext:
        "Calming soak ● Cuticle care ● File & buff ● Trimming & shaping ● Mineral salt/sugar exfoliation ● Callus treatment ● Collagen & keratin therapy socks ● Extended massage ● Hot towel wrap",
    },
  },
  {
    type: "ITEM",
    id: "MYHSHC25RQEDXV2DE7MJLMLG",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Soft gel extension",
      description:
        "Gel-X is a healthier, more natural looking & feeling alternative to traditional acrylic extension. This service comes with our Basic manicure service.",
      abbreviation: "Soft",
      labelColor: "86B73E",
      categoryId: "42Q7FDU26NEHTPIAL66WRWTA",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "FURESAOPHXLC7DNCMA7PZHPC",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "MYHSHC25RQEDXV2DE7MJLMLG",
            name: "Regular",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "8500",
              currency: "USD",
            },
            serviceDuration: "4200000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMSzK-FIQ2k6FSEU",
              "TMCwFyeMexqTdxw4",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Gel-X is a healthier, more natural looking &amp; feeling alternative to traditional acrylic extension. This service comes with our Basic manicure service. </p>",
      descriptionPlaintext:
        "Gel-X is a healthier, more natural looking & feeling alternative to traditional acrylic extension. This service comes with our Basic manicure service.",
    },
  },
  {
    type: "ITEM",
    id: "Q5LXFJ6AJXCOM6ON4IFU6ZOR",
    updatedAt: "2023-08-18T03:34:30.852Z",
    version: "1692329670852",
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: "Swarovski decor (each)",
      description: "Nails adorned with sparkling Swarovski crystals.",
      categoryId: "6KFSXPVFALGRCVN4FD3NN4DI",
      taxIds: ["U3KR6ER3VF5MWEM5OXEXK2TJ"],
      variations: [
        {
          type: "ITEM_VARIATION",
          id: "H6WKWYMUIP6X622YEWCS3IV3",
          updatedAt: "2023-08-18T03:34:30.852Z",
          version: "1692329670852",
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: "Q5LXFJ6AJXCOM6ON4IFU6ZOR",
            name: "Regular",
            ordinal: 1,
            pricingType: "FIXED_PRICING",
            priceMoney: {
              amount: "500",
              currency: "USD",
            },
            serviceDuration: "600000",
            availableForBooking: true,
            sellable: true,
            stockable: true,
            teamMemberIds: [
              "TMCwFyeMexqTdxw4",
              "TMSzK-FIQ2k6FSEU",
              "TMNWxmtV8EGB9S9F",
              "TMZOXcfnaorAtnO-",
            ],
          },
        },
      ],
      productType: "APPOINTMENTS_SERVICE",
      skipModifierScreen: false,
      descriptionHtml:
        "<p>Nails adorned with sparkling Swarovski crystals.</p>",
      descriptionPlaintext: "Nails adorned with sparkling Swarovski crystals.",
    },
  },
];
